<?php
/**
 * TL_ROOT/system/modules/visitors/languages/nl/default.php 
 * 
 * TYPOlight extension: visitors 1.3.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['visitors']['VisitorsOnlineCountLegend'] = "Online:";
$GLOBALS['TL_LANG']['visitors']['VisitorsStartDateLegend'] = "Telt sinds:";
$GLOBALS['TL_LANG']['visitors']['TotalVisitCountLegend'] = "Totaal aantal bezoeken:";
$GLOBALS['TL_LANG']['visitors']['TotalHitCountLegend'] = "Totaal aantal hits:";
$GLOBALS['TL_LANG']['visitors']['TodayVisitCountLegend'] = "Bezoeken vandaag:";
$GLOBALS['TL_LANG']['visitors']['TodayHitCountLegend'] = "Hits vandaag:";
$GLOBALS['TL_LANG']['visitors']['AverageVisitsLegend'] = "Bezoekers per dag:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_yes'] = "ja";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_no'] = "nee";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['name'] = "Naam";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['active'] = "Actief";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['date'] = "Datum";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['startdate'] = "Telt sinds";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['total'] = "Totaal aantal";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['visit'] = "Bezoeken";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['hit'] = "Hits";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['modname'] = "Visitors Module";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['select'] = "Selecteer";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['kat'] = "Categorie";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export'] = "Export";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export_button_title'] = "Deze knop opent een nieuw venster.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export_headline'] = "Categorie,ID,Naam,Gepubliceerd,Datum,Bezoeken,Hits";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['not_defined'] = "Niet gedefinieerd";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['no_data'] = "Geen gegevens bekend voor deze categorie.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['no_stat_data'] = "Geen statistieken bekend voor deze teller.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['period'] = "Periode";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['today'] = "Vandaag";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['yesterday'] = "Gisteren";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_week'] = "Deze week";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_week'] = "Vorige week";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_month'] = "Deze maand";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_month'] = "Vorige maand";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['reset'] = "Reset";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['zero'] = "De tellers worden gereset naar nul.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['zero_confirm'] = "Weet u zeker dat u de teller(s) wil resetten (hits en bezoeken)?";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_visits'] = "Bezoekers per dag:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_hits'] = "Hits per dag:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_legend'] = "Gemiddelden";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['parameter'] = "Parameter";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['initial_values'] = "Beginwaarden";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_version'] = "Versies";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_lang'] = "Talen";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_os'] = "Besturingssystemen";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_top10'] = "Browser top-10";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_top20'] = "Browser top-20";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_definition'] = "Browser definitie";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_unknown'] = "Onbekend";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_known'] = "Bekend";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_osdif'] = "anders";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_no_data'] = "Geen gegevens beschikbaar.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_red'] = "rood";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_green'] = "groen";
 
?>
