<?php
/**
 * TL_ROOT/system/modules/visitors/languages/nl/explain.php 
 * 
 * TYPOlight extension: visitors 1.3.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['0'] = "Naam";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['1'] = "De naam verschijnt als een kop in het frontend.";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['1']['0'] = "Begindatum";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['1']['1'] = "De begindatum wordt alleen gebruikt ter informatie.<br />Deze datum zal in het frontend weergegeven worden.<br />Deze datum beïnvloed niet het begin van het tellen!<br />Als de regel leeg blijft, wordt er niets weergegeven in het frontend.";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['2']['0'] = "HTTP_USER_AGENT partial identifier";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['2']['1'] = "Als u hier een unieke identifier opgeeft, die overeenkomt met een identifier die gekoppeld is aan uw browser, kan worden voorkomen dat uw bezoeken aan de site worden geteld.<br />Meer hierover in de documentatie van deze module.";
 
?>
