<?php
/**
 * TL_ROOT/system/modules/visitors/languages/nl/modules.php 
 * 
 * TYPOlight extension: visitors 1.3.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['visitors']['0'] = "Visitors";
$GLOBALS['TL_LANG']['MOD']['visitors']['1'] = "Deze module maakt het mogelijk om hits en bezoeken aan uw website te tellen.";
$GLOBALS['TL_LANG']['MOD']['visitorstat']['0'] = "Bezoekstatistieken";
$GLOBALS['TL_LANG']['MOD']['visitorstat']['1'] = "Bezoekstatistieken van de module Visitors.";
$GLOBALS['TL_LANG']['FMD']['visitors']['0'] = "Visitors";
$GLOBALS['TL_LANG']['FMD']['visitors']['1'] = "Visitors";
 
?>
