<?php
/**
 * TL_ROOT/system/modules/visitors/languages/nl/tl_module.php 
 * 
 * TYPOlight extension: visitors 1.3.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['visitors_categories']['0'] = "Categoriën bezoekers";
$GLOBALS['TL_LANG']['tl_module']['visitors_categories']['1'] = "Selecteer de categoriën van bezoekers.";
$GLOBALS['TL_LANG']['tl_module']['visitors_useragent']['0'] = "Niet tellen voor deze HTTP_USER_AGENT partial identifier";
$GLOBALS['TL_LANG']['tl_module']['visitors_useragent']['1'] = "Als u hier een unieke identifier opgeeft, die overeenkomt met een identifier die gekoppeld is aan uw browser, kan worden voorkomen dat uw bezoeken aan de site worden geteld.<br />Meer hierover in de documentatie van deze module.";
 
?>
