<?php
/**
 * TL_ROOT/system/modules/visitors/languages/nl/tl_visitors_category.php 
 * 
 * TYPOlight extension: visitors 1.3.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors_category']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_visitors_category']['title']['1'] = "Geef de titel van de categorie.";
$GLOBALS['TL_LANG']['tl_visitors_category']['visitors_template']['0'] = "Teller template";
$GLOBALS['TL_LANG']['tl_visitors_category']['visitors_template']['1'] = "Kies de teller template. Teller template bestanden beginnen met <em>mod_visitors_fe_</em>.";
$GLOBALS['TL_LANG']['tl_visitors_category']['tstamp']['0'] = "Herzieningsdatum";
$GLOBALS['TL_LANG']['tl_visitors_category']['tstamp']['1'] = "Datum en tijd van de laatste herziening";
$GLOBALS['TL_LANG']['tl_visitors_category']['title_legend'] = "Titel en teller template";
$GLOBALS['TL_LANG']['tl_visitors_category']['deleteConfirm'] = "Als u een categorie wist, zullen alle bezoekstatistieken in deze categorie ook gewist worden. Weet u zeker dat u categorie ID %s wilt wissen?";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['0'] = "Nieuwe categorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['1'] = "Maak een nieuwe categorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['0'] = "Bewerk categorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['1'] = "Bewerk categorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['0'] = "Kopieer categorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['1'] = "Kopieer categorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['0'] = "Wis categorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['1'] = "Wis categorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['0'] = "Categorie details";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['1'] = "Toon de details van categorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['0'] = "Categorie statistieken";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['1'] = "Toon de statistieken voor categorie ID %s";
 
?>
