<?php
/**
 * TL_ROOT/system/modules/visitors/languages/it/default.php 
 * 
 * TYPOlight extension: visitors 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['visitors']['VisitorsOnlineCountLegend'] = "Online:";
$GLOBALS['TL_LANG']['visitors']['VisitorsStartDateLegend'] = "Contati dal:";
$GLOBALS['TL_LANG']['visitors']['TotalVisitCountLegend'] = "Visite totali:";
$GLOBALS['TL_LANG']['visitors']['TotalHitCountLegend'] = "Accessi totali:";
$GLOBALS['TL_LANG']['visitors']['TodayVisitCountLegend'] = "Visite oggi:";
$GLOBALS['TL_LANG']['visitors']['TodayHitCountLegend'] = "Accessi oggi:";
$GLOBALS['TL_LANG']['visitors']['AverageVisitsLegend'] = "Visitatori al giorno:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_yes'] = "sì";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_no'] = "no";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['name'] = "Nome";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['active'] = "Attivo";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['date'] = "Data";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['startdate'] = "Contati dal";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['total'] = "Numero totale";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['visit'] = "Visite";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['hit'] = "Accessi";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['modname'] = "Modulo Visitatori";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['select'] = "Per cortesia seleziona";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['kat'] = "Categoria";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export'] = "Export";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export_button_title'] = "Il pulsante apre una nuova finestra.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export_headline'] = "Categoria,ID,Nome,Pubblicato,Data,Visite,Accessi";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['not_defined'] = "Non definito";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['no_data'] = "Nessun dato disponibile per questa categoria.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['no_stat_data'] = "Nessun dato statistico per questo contatore.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['period'] = "Periodo";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['today'] = "Oggi";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['yesterday'] = "Ieri";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_week'] = "Settimana corrente";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_week'] = "Settimana scorsa";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_month'] = "Ultima settimana";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_month'] = "Ultimo mese";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['reset'] = "Reset";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['zero'] = "I contatori statistici saranno resettati a zero.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['zero_confirm'] = "Vuoi veramente resettare i contatori statistici (accessi e visite)?";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_visits'] = "Visitatori al giorno:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_hits'] = "Accessi al giorno:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_legend'] = "Media";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['parameter'] = "Parametro";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['initial_values'] = "Valori iniziali";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_red']   = 'rosso';
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_green'] = 'verde'; 

?>