<?php
/**
 * TL_ROOT/system/modules/visitors/languages/it/explain.php 
 * 
 * TYPOlight extension: visitors 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['0'] = "Nome";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['1'] = "Il nome compare come intestazione nel frontend.";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['1']['0'] = "Data di inizio";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['1']['1'] = "La data d'inizio ha una funzione puramente informativa.<br />Nel frontend questa data sarà visualizzabile<br />Questo non influisce sull'inizio della conta!<br />Quando il campo rimane vuoto, lo spazio bianco non compare, resta nascosto nel frontend.";
 
?>
