<?php
/**
 * TL_ROOT/system/modules/visitors/languages/it/modules.php 
 * 
 * TYPOlight extension: visitors 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['visitors']['0'] = "Visitatori";
$GLOBALS['TL_LANG']['MOD']['visitors']['1'] = "Questo modulo ti permette di contare gli accessi e le visite al tuo sito web.";
$GLOBALS['TL_LANG']['MOD']['visitorstat']['0'] = "Statistiche visitatori";
$GLOBALS['TL_LANG']['MOD']['visitorstat']['1'] = "Statistiche visitatori dal modulo visitatori.";
$GLOBALS['TL_LANG']['FMD']['visitors']['0'] = "Visitatori";
$GLOBALS['TL_LANG']['FMD']['visitors']['1'] = "Visitatori";

?>