<?php
/**
 * TL_ROOT/system/modules/visitors/languages/it/tl_module.php 
 * 
 * TYPOlight extension: visitors 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['visitors_categories']['0'] = "Categorie visitatori";
$GLOBALS['TL_LANG']['tl_module']['visitors_categories']['1'] = "Per cortesia seleziona le categorie di visitatori che vuoi aggiungere.";
 
?>
