<?php
/**
 * TL_ROOT/system/modules/visitors/languages/it/tl_visitors_category.php 
 * 
 * TYPOlight extension: visitors 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors_category']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_visitors_category']['title']['1'] = "Per cortesia inserisci il titolo della categoria.";
$GLOBALS['TL_LANG']['tl_visitors_category']['visitors_template']['0'] = "Template contatore";
$GLOBALS['TL_LANG']['tl_visitors_category']['visitors_template']['1'] = "Per cortesia scegli il Template-Contatore. La template del contatoer parte con  Counter template files start with <em>mod_visitors_fe_</em>.";
$GLOBALS['TL_LANG']['tl_visitors_category']['tstamp']['0'] = "Data revisione";
$GLOBALS['TL_LANG']['tl_visitors_category']['tstamp']['1'] = "Data e ora dell'ultima revisione";
$GLOBALS['TL_LANG']['tl_visitors_category']['title_legend'] = "Titolo e contatore template";
$GLOBALS['TL_LANG']['tl_visitors_category']['deleteConfirm'] = "Cancellare una categoria implica la cancellazione di tutte le informazioni connesse al contatore. Vuoi veramente cancellare la categoria ID %s?";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['0'] = "Nuova categoria";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['1'] = "Crea una nuova categoria";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['0'] = "Modifica categoria";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['1'] = "Modifica categoria ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['0'] = "Copia categoria";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['1'] = "Copia categoria ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['0'] = "Cancella categoria";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['1'] = "Cancella categoria ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['0'] = "Dettagli categoria";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['1'] = "Mostra i dettagli della categoria ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['0'] = "Statistiche categoria";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['1'] = "Molstra le statistiche contatore per la categoria ID %s";
 
?>
