<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fa/default.php 
 * 
 * Contao extension: visitors 2.6.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['visitors']['VisitorsOnlineCountLegend'] = "برخط:";
$GLOBALS['TL_LANG']['visitors']['VisitorsStartDateLegend'] = "شمارش از:";
$GLOBALS['TL_LANG']['visitors']['TotalVisitCountLegend'] = "بازدیدکنندگان کل:";
$GLOBALS['TL_LANG']['visitors']['TotalHitCountLegend'] = "کلیک کل:";
$GLOBALS['TL_LANG']['visitors']['TodayVisitCountLegend'] = "بازدید کنندگان امروز";
$GLOBALS['TL_LANG']['visitors']['TodayHitCountLegend'] = "کلیک‌های امروز";
$GLOBALS['TL_LANG']['visitors']['AverageVisitsLegend'] = "بازدید در هر روز:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_yes'] = "بلی";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_no'] = "خیر";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['name'] = "نام";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['active'] = "فعال";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['date'] = "تاریخ";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['startdate'] = "شمارش از";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['total'] = "تعداد کل";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['visit'] = "بازدیدها";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['hit'] = "کلیک‌ها";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['modname'] = "ماژول بازدیدکنندگان";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['select'] = "انتخاب نمایید";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['kat'] = "شاخه";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export'] = "خروجی";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['not_defined'] = "تعریف نشده";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['period'] = "دوره";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['today'] = "امروز";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['yesterday'] = "دیروز";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_week'] = "هفته جاری";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_week'] = "هفته آخر";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_month'] = "ماه جاری";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_month'] = "ماه آخر";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['reset'] = "بازتنظیم";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_visits'] = "بازدیدکننده در هر روز:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_hits'] = "کلیک در هر روز";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_legend'] = "میانگین";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['parameter'] = "پارامتر";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['initial_values'] = "مقادیر اولیه";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_version'] = "ویرایش‌ها";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_lang'] = "زبان‌ها";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_os'] = "سیستم‌عامل‌ها";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_top10'] = "مرور ۱۰ برتر";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_top20'] = "مرور ۲۰ برتر";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_unknown'] = "نامعلوم";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_known'] = "معلوم";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_osdif'] = "متقاوت";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_red'] = "قرمز";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_green'] = "سبز";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchengine_no_data'] = "داده‌ای موجود نیست.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchenginekeywords'] = "کلیدواژه‌ها";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchengine'] = "موتور جستجو";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['over'] = "از طریق";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['number'] = "شماره";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['referrer_dns'] = "دامنه";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['referrer_direct'] = "درخواست مستقیم";
 
?>
