<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fa/explain.php 
 * 
 * Contao extension: visitors 2.5.4 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2009..2011 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['0'] = "نام";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['1']['0'] = "تاریخ شروع";
 
?>
