<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fa/tl_visitors.php 
 * 
 * Contao extension: visitors 2.6.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors']['visitors_name']['0'] = "نام";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_startdate']['0'] = "تاریخ شروع";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_visit_start']['0'] = "مقدار اولیه بازدیدها";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_hit_start']['0'] = "مقدار اولیه کلیک‌ها";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_average']['0'] = "بازدیدها در روز";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_thousands_separator']['0'] = "جداکننده هزار";
$GLOBALS['TL_LANG']['tl_visitors']['published']['0'] = "منتشر شده";
$GLOBALS['TL_LANG']['tl_visitors']['not_defined'] = "تعریف نشده";
$GLOBALS['TL_LANG']['tl_visitors']['title_legend'] = "نام و تاریخ شروع";
$GLOBALS['TL_LANG']['tl_visitors']['start_legend'] = "مقادیر اولیه انتخابی";
$GLOBALS['TL_LANG']['tl_visitors']['publish_legend'] = "تنظیمات انتشار";
$GLOBALS['TL_LANG']['tl_visitors']['design_legend'] = "طراحی";
$GLOBALS['TL_LANG']['tl_visitors']['new']['0'] = "شمارنده جدید";
$GLOBALS['TL_LANG']['tl_visitors']['new']['1'] = "ایجاد شمارنده جدید";
$GLOBALS['TL_LANG']['tl_visitors']['edit']['0'] = "ویرایش شمارنده";
$GLOBALS['TL_LANG']['tl_visitors']['edit']['1'] = "ویرایش شمارنده شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors']['copy']['0'] = "تکثیر شمارنده";
$GLOBALS['TL_LANG']['tl_visitors']['copy']['1'] = "تکثیر شمارنده شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors']['delete']['0'] = "حذف شمارنده";
$GLOBALS['TL_LANG']['tl_visitors']['delete']['1'] = "حذف شمارنده شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors']['show']['0'] = "جزئیات";
$GLOBALS['TL_LANG']['tl_visitors']['show']['1'] = "نمایش جزئیات شمارنده شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors']['editheader']['0'] = "ویرایش دسته";
$GLOBALS['TL_LANG']['tl_visitors']['editheader']['1'] = "ویرایش این دسته";
 
?>
