<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fa/tl_visitors_referrer.php 
 * 
 * Contao extension: visitors 2.6.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors_referrer']['details_for'] = "جزئیات برای";
$GLOBALS['TL_LANG']['tl_visitors_referrer']['number'] = "شماره";
 
?>
