<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fa/tl_visitors.php 
 * 
 * Contao extension: visitors 2.5.4 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2009..2011 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors']['visitors_name']['0'] = "نام";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_startdate']['0'] = "تاریخ شروع";
$GLOBALS['TL_LANG']['tl_visitors']['published']['0'] = "منتشر شده";
$GLOBALS['TL_LANG']['tl_visitors']['not_defined'] = "تعریف نشده";
$GLOBALS['TL_LANG']['tl_visitors']['design_legend'] = "طراحی";
$GLOBALS['TL_LANG']['tl_visitors']['new']['0'] = "شمارنده جدید";
$GLOBALS['TL_LANG']['tl_visitors']['new']['1'] = "ایجاد شمارنده جدید";
$GLOBALS['TL_LANG']['tl_visitors']['edit']['0'] = "ویرایش شمارنده";
$GLOBALS['TL_LANG']['tl_visitors']['show']['0'] = "جزئیات";
 
?>
