<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fa/tl_visitors_category.php 
 * 
 * Contao extension: visitors 2.6.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors_category']['title']['0'] = "عنوان";
$GLOBALS['TL_LANG']['tl_visitors_category']['tstamp']['0'] = "تاریخ بازنگری";
$GLOBALS['TL_LANG']['tl_visitors_category']['visitors_cache_mode']['0'] = "حالت شمارش";
$GLOBALS['TL_LANG']['tl_visitors_category']['cache_legend'] = "حالت شمارش";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['0'] = "دسته جدید";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['1'] = "ایجاد  یک دسته جدید";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['0'] = "ویرایش دسته";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['1'] = "ویرایش دسته شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['0'] = "کپی دسته";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['1'] = "کپی دسته شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['0'] = "حذف دسته";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['1'] = "حذف دسته شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['0'] = "جزئیات دسته";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['1'] = "جزئیات دسته شناسه %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['0'] = "آمار دسته";
 
?>
