<?php
/**
 * TL_ROOT/system/modules/visitors/languages/sl/default.php 
 * 
 * TYPOlight extension: visitors 1.0.0 stable 
 * Slovenian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Slavko Šketa (slbones) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['visitors']['VisitorsOnlineCountLegend'] = "Online:";
$GLOBALS['TL_LANG']['visitors']['VisitorsStartDateLegend'] = "Štetje od:";
$GLOBALS['TL_LANG']['visitors']['TotalVisitCountLegend'] = "Skupaj obiskov:";
$GLOBALS['TL_LANG']['visitors']['TotalHitCountLegend'] = "Skupaj klikov:";
$GLOBALS['TL_LANG']['visitors']['TodayVisitCountLegend'] = "Obiskov danes:";
$GLOBALS['TL_LANG']['visitors']['TodayHitCountLegend'] = "Klikov danes:";
$GLOBALS['TL_LANG']['visitors']['AverageVisitsLegend'] = "Obiskov na dan:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_yes'] = "da";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_no'] = "ne";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['name'] = "Ime";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['active'] = "Aktiven";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['date'] = "Datum";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['startdate'] = "Štejem od";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['total'] = "Celotno število";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['visit'] = "Obiskov";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['hit'] = "Klikov";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['modname'] = "Modul obiskovalcev";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['select'] = "Prosimo izberite";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['kat'] = "Kategorija";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export'] = "Pretvori";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export_button_title'] = "Gumb se odpre v novem oknu";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['not_defined'] = "Ni definirano";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['no_data'] = "Ni podatkov za to kategorijo";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['period'] = "Sektor";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['today'] = "Danes";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['yesterday'] = "Včeraj";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_week'] = "Trenutni teden";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_week'] = "Prejšnji teden";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_month'] = "Trenutni mesec";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_month'] = "Prejšnji mesec";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['reset'] = "Resetiraj";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['zero'] = "Števec statistike bo resetiran na nič";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['zero_confirm'] = "Resnično hočete resetirati števec statistike (kliki in obiski)?";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_visits'] = "Obiskov na dan:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_hits'] = "Klikov na dan:";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_legend'] = "Povprečje";
 
?>
