<?php
/**
 * TL_ROOT/system/modules/visitors/languages/sl/explain.php 
 * 
 * TYPOlight extension: visitors 1.0.0 stable 
 * Slovenian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Slavko Šketa (slbones) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['0'] = "Ime";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['1'] = "Ime se prikaže kot naslov v front-endu";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['1']['0'] = "Začetni dazum";
 
?>
