<?php
/**
 * TL_ROOT/system/modules/visitors/languages/sl/modules.php 
 * 
 * TYPOlight extension: visitors 1.0.0 stable 
 * Slovenian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Slavko Šketa (slbones) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['visitors']['0'] = "Obiskovalci";
$GLOBALS['TL_LANG']['MOD']['visitors']['1'] = "Ta modul vam omogoča štetje klikov in obiskov na vaši spletni strani.";
$GLOBALS['TL_LANG']['MOD']['visitorstat']['0'] = "Statistika obiskovalca";
$GLOBALS['TL_LANG']['MOD']['visitorstat']['1'] = "Statistika obiskovalca iz modula obiskovalcev";
$GLOBALS['TL_LANG']['FMD']['visitors']['0'] = "Obiskovalci";
$GLOBALS['TL_LANG']['FMD']['visitors']['1'] = "Obiskovalci";
 
?>