<?php
/**
 * TL_ROOT/system/modules/visitors/languages/sl/tl_visitors_category.php 
 * 
 * TYPOlight extension: visitors 1.0.0 stable 
 * Slovenian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Slavko Šketa (slbones) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors_category']['title']['0'] = "Naslov";
$GLOBALS['TL_LANG']['tl_visitors_category']['title']['1'] = "Prosimo vnesite naslov kategorije";
$GLOBALS['TL_LANG']['tl_visitors_category']['visitors_template']['0'] = "Templeate števca";
$GLOBALS['TL_LANG']['tl_visitors_category']['tstamp']['0'] = "Datum revizije";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['0'] = "Nova kategorija";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['1'] = "Ustvari novo kategorijo";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['0'] = "Uredi kategorijo";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['1'] = "Uredi kategorijo ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['0'] = "Kopiraj kategorijo";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['1'] = "Kopiraj kategorijo ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['0'] = "Izbriši kategorijo";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['1'] = "Izbriši kategorijo ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['0'] = "Podrobnosti kategorije";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['1'] = "Prikaži podrobnosti kategorije ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['0'] = "Statistika kategorije";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['1'] = "Prikaži števec statistike za kategorijo ID %s";
 
?>
