<?php
/**
 * TL_ROOT/system/modules/visitors/languages/sl/tl_visitors.php 
 * 
 * TYPOlight extension: visitors 1.0.0 stable 
 * Slovenian translation file 
 * 
 * Copyright : &copy; 2009 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Slavko Šketa (slbones) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors']['visitors_name']['0'] = "Ime";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_name']['1'] = "Prosimo vpišite ime za ta števec.";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_startdate']['0'] = "Začetni datum";
$GLOBALS['TL_LANG']['tl_visitors']['visitors_average']['0'] = "Obiskovalce na dan";
$GLOBALS['TL_LANG']['tl_visitors']['published']['0'] = "Objavljeno";
$GLOBALS['TL_LANG']['tl_visitors']['published']['1'] = "Števec ne bo viden na spletni strani dokler ni objavljen.";
$GLOBALS['TL_LANG']['tl_visitors']['not_defined'] = "Ni definirano";
$GLOBALS['TL_LANG']['tl_visitors']['new']['0'] = "Nov števec";
$GLOBALS['TL_LANG']['tl_visitors']['new']['1'] = "Kreiraj nov števec";
$GLOBALS['TL_LANG']['tl_visitors']['edit']['0'] = "Uredi števec";
$GLOBALS['TL_LANG']['tl_visitors']['edit']['1'] = "Uredi števec ID %s";
$GLOBALS['TL_LANG']['tl_visitors']['copy']['0'] = "Dupliciraj števec";
$GLOBALS['TL_LANG']['tl_visitors']['copy']['1'] = "Dupliciraj števec ID %s";
$GLOBALS['TL_LANG']['tl_visitors']['delete']['0'] = "Izbriši števec";
$GLOBALS['TL_LANG']['tl_visitors']['delete']['1'] = "Izbriši števec ID %s";
$GLOBALS['TL_LANG']['tl_visitors']['show']['0'] = "Podrobnosti";
$GLOBALS['TL_LANG']['tl_visitors']['show']['1'] = "Prikaži podrobnosti števca ID %s";
$GLOBALS['TL_LANG']['tl_visitors']['editheader']['0'] = "Uredi kategorijo";
$GLOBALS['TL_LANG']['tl_visitors']['editheader']['1'] = "Uredi to kategorijo";
 
?>
