<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fr/default.php 
 * 
 * Contao extension: visitors 2.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['visitors']['VisitorsOnlineCountLegend'] = "En ligne :";
$GLOBALS['TL_LANG']['visitors']['TotalVisitCountLegend'] = "Total des visites :";
$GLOBALS['TL_LANG']['visitors']['TotalHitCountLegend'] = "Total des hits :";
$GLOBALS['TL_LANG']['visitors']['TodayVisitCountLegend'] = "Visites aujourd'hui :";
$GLOBALS['TL_LANG']['visitors']['TodayHitCountLegend'] = "Hits aujourd'hui :";
$GLOBALS['TL_LANG']['visitors']['AverageVisitsLegend'] = "Visiteurs par jour :";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_yes'] = "oui";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['pub_no'] = "non";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['name'] = "Nom";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['active'] = "Actif";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['date'] = "Date";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['startdate'] = "Compte depuis";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['total'] = "Nombre total";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['visit'] = "Visites";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['hit'] = "Hits";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['modname'] = "Module visiteurs";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['select'] = "Veuillez sélectionner";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['kat'] = "Catégorie";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export'] = "Exporter";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export_button_title'] = "Le bouton ouvre une nouvelle fenêtre.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['export_headline'] = "Catégorie,ID,Nom,Publié,Date,Visites,Hits";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['not_defined'] = "Non défini";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['no_data'] = "Aucune données disponible pour cette catégorie.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['no_stat_data'] = "Aucune données disponible pour ce compteur.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['period'] = "Période";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['today'] = "Aujourd'hui";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['yesterday'] = "Hier";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_week'] = "Semaine courante";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_week'] = "Semaine dernière";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['current_month'] = "Mois courant";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['last_month'] = "Mois dernnier";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['reset'] = "Mise à zéro";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['zero'] = "Le compteurve être remis à zéro.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_visits'] = "Visiteurs par jours :";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_hits'] = "Hits par jours :";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_legend'] = "Moyenne";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['average_tipp'] = "(30) / (60) = &Oslash; valeurs de 30 / 60 derniers jours";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['parameter'] = "Paramètre";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['initial_values'] = "Valeur initiale";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_version'] = "Version";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_lang'] = "Langue";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_os'] = "Système d'exploitation";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_top10'] = "Navigateur TOP 10";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_top20'] = "Navigateur TOP 20";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_definition'] = "Définition du navigateur";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_unknown'] = "Inconnu";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_known'] = "Connu";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_osdif'] = "différent";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['browser_no_data'] = "Aucune donnée disponible.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_red'] = "rouge";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['chart_green'] = "vert";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchenginekeywords_top'] = "Mots clés de recherche TOP 20";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchengines_top'] = "Moteurs de recherche TOP 20";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchengine_no_data'] = "Aucune donnée disponible.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchengine_data'] = "Valeurs des 60 derniers jours.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchenginekeywords'] = "Mot clé";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['searchengine'] = "Moteur de recherche";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['over'] = "via";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['number'] = "Nombre";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['referrer_top'] = "Référant TOP 30";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['referrer_dns'] = "Domaine";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['referrer_data'] = "Valeurs des 120 derniers jours.";
$GLOBALS['TL_LANG']['MSC']['tl_visitors_stat']['referrer_direct'] = "Requête directe";
$GLOBALS['TL_LANG']['MSC']['tl_vivitors_stat']['most_visitors'] = "Jour avec le plus de visiteurs";
$GLOBALS['TL_LANG']['MSC']['tl_vivitors_stat']['fewest_visitors'] = "Jour avec le moins de visiteurs";
$GLOBALS['TL_LANG']['MSC']['tl_vivitors_stat']['visitors_this_day'] = "Visites ce jour";
$GLOBALS['TL_LANG']['MSC']['tl_vivitors_stat']['hits_this_day'] = "Hits ce jour";
$GLOBALS['TL_LANG']['MSC']['tl_vivitors_stat']['currently online'] = "Actuellement en ligne";
 
?>
