<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fr/explain.php 
 * 
 * Contao extension: visitors 2.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['visitors_help']['0']['0'] = "Nom";
$GLOBALS['TL_LANG']['XPL']['visitors_help']['1']['0'] = "Date de départ";
$GLOBALS['TL_LANG']['XPL']['visitors_help_module']['0']['0'] = "HTTP_USER_AGENT identifiant partiel";
 
?>
