<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fr/modules.php 
 * 
 * Contao extension: visitors 2.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['visitors']['0'] = "Visiteurs";
$GLOBALS['TL_LANG']['MOD']['visitorstat']['0'] = "Statistiques des visiteurs";
$GLOBALS['TL_LANG']['FMD']['visitors']['0'] = "Visiteurs";
 
?>
