<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fr/tl_module.php 
 * 
 * Contao extension: visitors 2.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['visitors_categories']['0'] = "Catégorie des visiteurs";
$GLOBALS['TL_LANG']['tl_module']['visitors_template']['0'] = "Modèle du compteur";
 
?>
