<?php
/**
 * TL_ROOT/system/modules/visitors/languages/fr/tl_visitors_category.php 
 * 
 * Contao extension: visitors 2.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2009..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['0'] = "Nouvelle cétégorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['new']['1'] = "Créer une nouvelle catégorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['0'] = "Editer la catégorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['edit']['1'] = "Editer la catégorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['0'] = "Copier la catégorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['copy']['1'] = "Copier la catégorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['0'] = "Supprimer la catégorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['delete']['1'] = "Supprimer la catégorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['0'] = "Détails de la catégorie";
$GLOBALS['TL_LANG']['tl_visitors_category']['show']['1'] = "Afficher les détails de la catégorie ID %s";
$GLOBALS['TL_LANG']['tl_visitors_category']['stat']['0'] = "Statistiques de la catégorie";
 
?>
